name: CI

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Start Redis
        working-directory: ./docker
        run:  docker-compose up -d

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test
      - name: Run tests - clusters
        run: |
          node test-clusters.js
